version: '3'
services:
  node:
    build: .
    volumes:
      - ./src:/usr/app/src
    networks: 
      - inside
      - default
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    restart: always

  postgres:
    build: ./database/
    networks: 
      - inside
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

networks: 
  default:
  inside:
    internal: true
    name: internal network for ap and database