version: '3'
services:
  node:
    build: .
    volumes:
      - ./src:/usr/app/src
      - ./access.log:/usr/app/access.log
      - ./error.log:/usr/app/error.log
    networks: 
      - inside
      - default
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    restart: always
    command: sh -c './wait-for.sh ${POSTGRES_HOST}:${POSTGRES_PORT} -- npm run migrate && npm start:nest'

  postgres:
    build: ./database/
    container_name: postgres
    hostname: postgres
    networks: 
      inside: 
        aliases: 
          - postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
      
networks: 
  default:
  inside:
    internal: true
    name: internal network for ap and database